# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build a new app using xcode cloud signing"
  lane :beta_login do
    build_app(
    scheme: "CloudSigning",
    xcargs: "-allowProvisioningUpdates")

    #upload_to_testflight
  end

  desc "Build a new app using xcode cloud signing"
  lane :beta_key do
    build_app(
    scheme: "CloudSigning",
    xcargs: "-allowProvisioningUpdates -authenticationKeyIssuerID 69a6de8f-7623-47e3-e053-5b8c7c11a4d1 -authenticationKeyID 883JNHN66R -authenticationKeyPath /Users/uday/Work/garrison/Legion/Signing/cloud-signing/PrivateKeys/AuthKey_883JNHN66R.p8"
    )

    #upload_to_testflight
  end
end
